[package]
name = "player-skeleton-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio= "1.34.0"
reqwest = "0.11.22"
serde = "1.0.193"
serde_json = "1.0.108"
lazy_static = "1.4.0"