[package]
name = "player-skeleton-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }  # For Sending network calls in parallel
reqwest = { version = "0.11.22", features = ["blocking"] }
rayon = "1.8.0" # For parallelism
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
crosstown_bus = "0.8.1" #RabbitMQ

env_logger = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.20"