apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-skeleton-rust.fullname" . }}
  labels:
    {{- include "player-skeleton-rust.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | int }} 
  selector:
    matchLabels:
      {{- include "player-skeleton-rust.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "player-skeleton-rust.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "player-skeleton-rust.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- with .Values.service.my }}
            - name: {{ .portName | lower }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "player-skeleton-rust.fullname" . }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
              {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.logVol.mountPath }}
              name: {{ .Values.logVol.name }}
      volumes:
        - name: {{ .Values.logVol.name }}
          emptyDir:
            sizeLimit: {{ .Values.logVol.sizeLimit }}
