apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-skeleton-rust.fullname" . }}
  labels:
  {{- include "player-skeleton-rust.labels" . | nindent 4 }}
spec:
{{- range .Values.service.ports }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- end }}
  selector:
  {{- include "player-skeleton-rust.selectorLabels" . | nindent 4 }}
